export const plans = [
  {
    id: 'basic',
    name: 'Basic',
    description: 'Perfect for small agencies getting started',
    price: 29,
    features: [
      '3 Workspaces',
      '10GB Storage',
      'Basic Support',
      'Standard Integrations',
      'Email Notifications',
    ],
  },
  {
    id: 'pro',
    name: 'Pro',
    description: 'Ideal for growing agencies',
    price: 79,
    featured: true,
    features: [
      '10 Workspaces',
      '50GB Storage',
      'Priority Support',
      'Advanced Integrations',
      'Custom Branding',
      'API Access',
      'Analytics Dashboard',
    ],
  },
  {
    id: 'business',
    name: 'Business',
    description: 'For large agencies with multiple teams',
    price: 199,
    features: [
      'Unlimited Workspaces',
      '200GB Storage',
      '24/7 Support',
      'Premium Integrations',
      'Advanced Security',
      'Custom Workflows',
      'Team Training',
      'Dedicated Account Manager',
    ],
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    description: 'Custom solutions for large organizations',
    price: null,
    features: [
      'Custom Workspace Limit',
      'Unlimited Storage',
      'White-label Solution',
      'Custom Integrations',
      'Enterprise Security',
      'SLA Guarantee',
      'Onboarding Support',
      'Custom Development',
    ],
  },
];